In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv('Train.csv')

## Explore the data 

In [3]:
data.head()

timestamp  Soil humidity 1  Irrigation field 1  Soil humidity 2  \
0  2019-02-23 00:00:00            67.92                 0.0            55.72   
1  2019-02-23 00:05:00            67.89                 0.0            55.74   
2  2019-02-23 00:10:00            67.86                 0.0            55.77   
3  2019-02-23 00:15:00            67.84                 0.0            55.79   
4  2019-02-23 00:20:00            67.81                 0.0            55.82   

   Irrigation field 2  Soil humidity 3  Irrigation field 3  Soil humidity 4  \
0                 0.0            -1.56                 1.0            26.57   
1                 0.0            -1.51                 1.0            26.58   
2                 0.0            -1.47                 1.0            26.59   
3                 0.0            -1.42                 1.0            26.61   
4                 0.0            -1.38                 1.0            26.62   

   Irrigation field 4  Air temperature (C)  Air humidity (%)  Pressure (KPa)  \
0                 1.0                19.52             55.04          101.50   
1                 1.0                19.49             55.17          101.50   
2                 1.0                19.47             55.30          101.51   
3                 1.0                19.54             54.20          101.51   
4                 1.0                19.61             53.09          101.51   

   Wind speed (Km/h)  Wind gust (Km/h)  Wind direction (Deg)  
0               2.13              6.30                225.00  
1               2.01             10.46                123.75  
2               1.90             14.63                 22.50  
3               2.28             16.08                123.75  
4               2.66             17.52                225.00

In [4]:
data.shape

(28049, 15)

In [5]:
data.describe()

Soil humidity 1  Irrigation field 1  Soil humidity 2  \
count      8917.000000        10066.000000     26304.000000   
mean         63.025653            0.177727        18.767424   
std           9.801099            0.382302        22.903736   
min          36.000000            0.000000       -45.000000   
25%          58.210000            0.000000         3.850000   
50%          63.000000            0.000000        23.000000   
75%          68.000000            0.000000        35.310000   
max          88.000000            1.000000        59.000000   

       Irrigation field 2  Soil humidity 3  Irrigation field 3  \
count        28029.000000     16086.000000        17236.000000   
mean             0.095615        25.046062            0.245243   
std              0.294068        19.998016            0.430243   
min              0.000000       -38.000000            0.000000   
25%              0.000000        10.220000            0.000000   
50%              0.000000        26.610000            0.000000   
75%              0.000000        41.360000            0.000000   
max              1.000000        68.000000            1.000000   

       Soil humidity 4  Irrigation field 4  Air temperature (C)  \
count     26306.000000        28029.000000         23995.000000   
mean         17.512501            0.211531            24.263780   
std          14.247310            0.408401             6.756751   
min         -30.000000            0.000000            11.220000   
25%           8.000000            0.000000            18.580000   
50%          19.600000            0.000000            22.150000   
75%          29.050000            0.000000            29.590000   
max          47.000000            1.000000            45.560000   

       Air humidity (%)  Pressure (KPa)  Wind speed (Km/h)  Wind gust (Km/h)  \
count      23995.000000    23995.000000       23995.000000      23995.000000   
mean          58.521052      101.131418           9.896898         41.744905   
std           30.073448        0.218448           4.325666         24.168987   
min            0.590000      100.500000           0.000000          0.000000   
25%           33.980000      100.980000           6.830000         21.820000   
50%           61.310000      101.120000           9.530000         37.240000   
75%           86.360000      101.260000          12.460000         59.275000   
max           96.000000      101.860000          31.360000        133.330000   

       Wind direction (Deg)  
count          23995.000000  
mean              93.983796  
std              100.502500  
min                0.000000  
25%               22.500000  
50%               22.500000  
75%              180.000000  
max              337.500000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28049 entries, 0 to 28048
Data columns (total 15 columns):
timestamp               28049 non-null object
Soil humidity 1         8917 non-null float64
Irrigation field 1      10066 non-null float64
Soil humidity 2         26304 non-null float64
Irrigation field 2      28029 non-null float64
Soil humidity 3         16086 non-null float64
Irrigation field 3      17236 non-null float64
Soil humidity 4         26306 non-null float64
Irrigation field 4      28029 non-null float64
Air temperature (C)     23995 non-null float64
Air humidity (%)        23995 non-null float64
Pressure (KPa)          23995 non-null float64
Wind speed (Km/h)       23995 non-null float64
Wind gust (Km/h)        23995 non-null float64
Wind direction (Deg)    23995 non-null float64
dtypes: float64(14), object(1)
memory usage: 3.2+ MB


In [7]:
data.isnull().sum()

timestamp                   0
Soil humidity 1         19132
Irrigation field 1      17983
Soil humidity 2          1745
Irrigation field 2         20
Soil humidity 3         11963
Irrigation field 3      10813
Soil humidity 4          1743
Irrigation field 4         20
Air temperature (C)      4054
Air humidity (%)         4054
Pressure (KPa)           4054
Wind speed (Km/h)        4054
Wind gust (Km/h)         4054
Wind direction (Deg)     4054
dtype: int64

In [8]:
data.columns

Index(['timestamp', 'Soil humidity 1', 'Irrigation field 1', 'Soil humidity 2',
       'Irrigation field 2', 'Soil humidity 3', 'Irrigation field 3',
       'Soil humidity 4', 'Irrigation field 4', 'Air temperature (C)',
       'Air humidity (%)', 'Pressure (KPa)', 'Wind speed (Km/h)',
       'Wind gust (Km/h)', 'Wind direction (Deg)'],
      dtype='object')

In [9]:
data = data.drop(['Irrigation field 1', 'Irrigation field 2', 'Irrigation field 3', 'Irrigation field 4', 'Air temperature (C)',
       'Air humidity (%)', 'Pressure (KPa)', 'Wind speed (Km/h)',
       'Wind gust (Km/h)', 'Wind direction (Deg)'], axis = 1)

In [10]:
data.head()

timestamp  Soil humidity 1  Soil humidity 2  Soil humidity 3  \
0  2019-02-23 00:00:00            67.92            55.72            -1.56   
1  2019-02-23 00:05:00            67.89            55.74            -1.51   
2  2019-02-23 00:10:00            67.86            55.77            -1.47   
3  2019-02-23 00:15:00            67.84            55.79            -1.42   
4  2019-02-23 00:20:00            67.81            55.82            -1.38   

   Soil humidity 4  
0            26.57  
1            26.58  
2            26.59  
3            26.61  
4            26.62

In [11]:
solid1 = data.drop(['Soil humidity 2', 'Soil humidity 3', 'Soil humidity 4'], axis = 1)
solid2 = data.drop(['Soil humidity 1', 'Soil humidity 3', 'Soil humidity 4'], axis = 1)
solid3 = data.drop(['Soil humidity 2', 'Soil humidity 1', 'Soil humidity 4'], axis = 1)
solid4 = data.drop(['Soil humidity 2', 'Soil humidity 3', 'Soil humidity 1'], axis = 1)

In [12]:
solid1.shape, solid2.shape, solid3.shape ,solid4.shape

((28049, 2), (28049, 2), (28049, 2), (28049, 2))

In [13]:
time = "2019-02-23 00:00:00"

In [14]:
time.split(" ")[0].split("-")[0]

'2019'

In [15]:
def extract_timestamp(solid, field):
    solid.dropna(inplace=True)
    solid["year"] = solid.timestamp.str.split(" ", n = 1, expand = True)[0].str.split("-", n = 2, expand = True)[0].astype(int)
    solid["month"] = solid.timestamp.str.split(" ", n = 1, expand = True)[0].str.split("-", n = 2, expand = True)[1].astype(int)
    solid["day"] = solid.timestamp.str.split(" ", n = 1, expand = True)[0].str.split("-", n = 2, expand = True)[2].astype(int)
    solid["hour"] = solid.timestamp.str.split(" ", n = 1, expand = True)[1].str.split(":", n = 2, expand = True)[0].astype(int)
    solid["minute"] = solid.timestamp.str.split(" ", n = 1, expand = True)[1].str.split(":", n = 2, expand = True)[1].astype(int)
    solid["second"] = solid.timestamp.str.split(" ", n = 1, expand = True)[1].str.split(":", n = 2, expand = True)[2].astype(int)
    solid.insert(1, 'field ',np.zeros((solid.shape[0], 1), dtype = int) + field)
    solid = solid.drop(['timestamp'], axis = 1)
    solid.rename(columns={ solid.columns[1]: "target" }, inplace = True)
    return solid

In [16]:
solid1 = extract_timestamp(solid1, 1)
solid2 = extract_timestamp(solid2, 2)
solid3 = extract_timestamp(solid3, 3)
solid4 = extract_timestamp(solid4, 4)

In [17]:
solid1.head()

field   target  year  month  day  hour  minute  second
0       1   67.92  2019      2   23     0       0       0
1       1   67.89  2019      2   23     0       5       0
2       1   67.86  2019      2   23     0      10       0
3       1   67.84  2019      2   23     0      15       0
4       1   67.81  2019      2   23     0      20       0

In [18]:
allData = pd.concat([solid1, solid2, solid3, solid4]) 


In [19]:
allData.head()

field   target  year  month  day  hour  minute  second
0       1   67.92  2019      2   23     0       0       0
1       1   67.89  2019      2   23     0       5       0
2       1   67.86  2019      2   23     0      10       0
3       1   67.84  2019      2   23     0      15       0
4       1   67.81  2019      2   23     0      20       0

In [20]:
def print_unique(column):
    print("----------{}----------".format(column))
    print(allData[column].unique())

In [21]:
for i in allData.columns:
    print_unique(i)

----------field ----------
[1 2 3 4]
----------target----------
[67.92 67.89 67.86 ...  8.04 -4.34 -4.91]
----------year----------
[2019]
----------month----------
[2 3 4 5]
----------day----------
[23 24 25 26 27 28  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18
 19 20 21 22 29 30 31]
----------hour----------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
----------minute----------
[ 0  5 10 15 20 25 30 35 40 45 50 55]
----------second----------
[0]


In [22]:
allData = allData.drop(['year', 'second'], axis = 1)

In [23]:
X = allData.drop(['target'], axis = 1)

In [24]:
y = allData.target

In [62]:
y

0        67.92
1        67.89
2        67.86
3        67.84
4        67.81
5        67.78
6        67.76
7        67.73
8        67.70
9        67.68
10       67.65
11       67.62
12       67.59
13       67.57
14       67.54
15       67.51
16       67.49
17       67.46
18       67.43
19       67.41
20       67.38
21       67.35
22       67.32
23       67.30
24       67.27
25       67.24
26       67.22
27       67.19
28       67.16
29       67.14
         ...  
26276    -2.00
26277    -2.00
26278    -2.00
26279    -2.00
26280    -2.00
26281    -2.00
26282    -2.00
26283    -2.00
26284    -2.00
26285    -2.00
26286    -2.00
26287    -2.00
26288    -1.36
26289    -0.72
26290    -0.08
26291     0.56
26292     1.21
26293     1.85
26294     2.49
26295     3.13
26296     3.77
26297     4.41
26298     5.05
26299     5.69
26300     6.33
26366    33.00
26999    23.00
27197    23.00
27554    17.00
27791    16.00
Name: target, Length: 77613, dtype: float64

## Building the Model

In [25]:
X.head()

field   month  day  hour  minute
0       1      2   23     0       0
1       1      2   23     0       5
2       1      2   23     0      10
3       1      2   23     0      15
4       1      2   23     0      20

In [48]:
# train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 22)

In [40]:
# Standerdise the dataset
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [27]:
# building first model
from sklearn.linear_model import LinearRegression
clf_lr = LinearRegression()
clf_lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor()
regressor.fit(x_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [57]:
y_pred = regressor.predict(x_test)

In [58]:
MSE = np.mean((y_test-y_pred)**2)
RMSE = np.sqrt(MSE)
print(RMSE)

13.88351582547969


## Test 

In [33]:
testData = pd.read_csv('SampleSubmission.csv')

In [34]:
ids = testData.ID

In [35]:
testData["field"] = ids.str.split("x", n = 2, expand = True)[1].str.split(" ", n = 3, expand = True)[3].astype(int)
testData["month"] = ids.str.split("x", n = 1, expand = True)[0].str.split(" ", n = 2, expand = True)[0].str.split("-", n = 2, expand = True)[1].astype(int)
testData["day"] = ids.str.split("x", n = 1, expand = True)[0].str.split(" ", n = 2, expand = True)[0].str.split("-", n = 2, expand = True)[2].astype(int)
testData["hour"] = ids.str.split("x", n = 1, expand = True)[0].str.split(" ", n = 2, expand = True)[1].str.split(":", n = 2, expand = True)[0].astype(int)
testData["minute"] = ids.str.split("x", n = 2, expand = True)[0].str.split(" ", n = 2, expand = True)[1].str.split(":", n = 2, expand = True)[1].astype(int)

In [36]:
tData = testData.iloc[:,2:]
testData = testData.drop(['field', 'month', 'day', 'hour', 'minute'], axis = 1)

In [228]:
tData = scaler.transform(tData)

In [229]:
tData

array([[-1.69845854, -0.63858729,  1.10984019,  1.51866856,  1.31183433],
       [-1.69845854, -0.63858729,  1.10984019,  1.51866856,  1.60202919],
       [-1.69845854, -0.63858729,  1.10984019,  1.6627309 , -1.5901143 ],
       ...,
       [ 1.17545081,  1.61461265,  1.80641777, -0.64226661,  0.44124974],
       [ 1.17545081,  1.61461265,  1.80641777, -0.64226661,  0.7314446 ],
       [ 1.17545081,  1.61461265,  1.80641777, -0.64226661,  1.02163946]])

In [59]:
y_sub = regressor.predict(tData)

In [60]:
testData.Values = y_sub

In [61]:
testData.to_csv('four.csv', index = False)